export const SEO_KEYWORDS = [
  'TrailAlert',
  'Trail Alert',
  'trails lienz',
  'trail lienz',
  'mtb lienz',
  'mountainbike lienz',
  'bike trails lienz',
  'forstwege sperren lienz',
  'forstweg sperre lienz',
  'wegsperre lienz',
  'wege sperre osttirol',
  'forstwege sperren osttirol',
  'trails osttirol',
  'mtb osttirol',
  'mountainbike osttirol',
  'trail status osttirol',
  'forstwege sperren tirol',
  'wegsperren tirol',
  'trails tirol',
  'mtb tirol',
  'mountainbike tirol',
  'trail status tirol',
  'mtb tour planen osttirol',
  'gpx route sperren',
  'tour check mountainbike',
  'hochstein trail',
  'zettersfeld trail',
  'lienzer dolomiten trails',
  'radweg sperre osttirol',
  'bike route sperre tirol',
  'wege offen lienz',
  'welcher trail ist offen',
  'trail sperre melden',
  'trail sperre app',
  'forstwege status',
]

export const SEO_ALTERNATE_BRAND = 'Trail Alert'

export const SEO_AREAS = [
  'Lienz',
  'Osttirol',
  'Tirol',
  'Lienzer Dolomiten',
  'Hochstein',
  'Zettersfeld',
]
